# Non Graded Challenge 4

Muhamad Bagus Septian - FTDS 13

In [2]:
import numpy as np

## 1. Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

In [6]:
tensor = np.array([
                    [
                        [23, 50], 
                        [7, 2]
                    ],
                    [
                        [57, 67],
                        [99, 43]
                    ],
                    [   [75, 21],
                        [57, 12]
                    ],
                    [   [87, 26],
                        [18, 84]
                    ]
                    ])

print(tensor)

[[[23 50]
  [ 7  2]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


## 2. Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

In [5]:
# Membuat matrix di python
A = np.array([[23, 50, 19],
                [7, 12, 109],
                [57, 67, 98]])

B = np.array([[17], [22], [19]])

print(A)
print(" ")
print(B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
 
[[17]
 [22]
 [19]]


In [7]:
# Perhitungan perkalian matrix

A @ B

array([[1852],
       [2454],
       [4305]])

## 3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$

In [8]:
x = np.array([[23, 50, 19],
                [7, 12, 109],
                [57, 67, 98]])

x

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [9]:
# Transpose matrix
x.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [10]:
# Perhitungan determinan matrix
np.linalg.det(x)

131344.0000000002

In [12]:
# Perhitungan inverse matrix
np.linalg.inv(x)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])