## Tipe data aljabar linear

### Berdasarkan array                      Pandas

- skalar - 0 D                      

- vektor - 1 D

- matriks - 2 D

- tensor - 3 D

In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]
        ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.shape

(3, 3)

In [6]:
a[1,:] # akses baris index ke- 1, semua kolom

array([4, 5, 6])

In [7]:
a[:,-1]

array([3, 6, 9])

In [8]:
a[2,1]

8

Type of Matrix

- Matrix persegi = jumlah kolom dan baris sama
- Matrix lower triangle = punya nilai kosong diatas -> np.tril
- Matrix upper triangle = punya nilai kosong dibawah -> np.triu
- Matrix diagonal = data hanya diagonal saja -> np.diag
- Matrix identity = data diagonal dan semua nilai sama -> np.eye

In [9]:
np.diag(a)

array([1, 5, 9])

In [11]:
np.diag(np.diag(a))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [12]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
a @ np.eye(3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## Operasi Arimatika Matrix

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
b = np.array([[2, 0, 1],
              [4, 2, 1],
              [1, 0, 2]])

b

array([[2, 0, 1],
       [4, 2, 1],
       [1, 0, 2]])

In [16]:
b.shape

(3, 3)

In [19]:
v = np.array([4,6,8])

Penjumlahan

In [17]:
# matriks terhadap skalar

10 + a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [18]:
# matrix terhadap matrix

a + b

array([[ 3,  2,  4],
       [ 8,  7,  7],
       [ 8,  8, 11]])

In [20]:
# matrix terhadap vector
a + v

array([[ 5,  8, 11],
       [ 8, 11, 14],
       [11, 14, 17]])

Pengurangan

In [21]:
# matriks terhadap skalar
10 - a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [22]:
# matrix terhadap matrix

a - b

array([[-1,  2,  2],
       [ 0,  3,  5],
       [ 6,  8,  7]])

Pembagian

In [23]:
# matriks terhadap skalar
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [24]:
# matrix terhadap matrix

a / b

C:\Users\Lled\AppData\Local\Temp\ipykernel_4832\2191693311.py:3: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([[0.5, inf, 3. ],
       [1. , 2.5, 6. ],
       [7. , inf, 4.5]])

Perkalian

In [28]:
# matrix terhadap skalar
10 * a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [29]:
# hadamar product (element wise multiplication)
# menggunakan simbol *

a * b

array([[ 2,  0,  3],
       [16, 10,  6],
       [ 7,  0, 18]])

In [30]:
# error karena beda shape
m * n

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [27]:
# matrix terhadap matrix
# menggunakan simbol @

m = np.array([[1,2,1],
            [4,0,2],
            [1,0,2]])

n = np.array([[2,0],
            [1,1],
            [4,2]])

print(m)
print(" ")
print(n)

[[1 2 1]
 [4 0 2]
 [1 0 2]]
 
[[2 0]
 [1 1]
 [4 2]]


In [26]:
m @ n

array([[ 8,  4],
       [16,  4],
       [10,  4]])

In [31]:
# error karena tidak komutatif
n @ m

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Transpose

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Inverse

In [34]:
b

array([[2, 0, 1],
       [4, 2, 1],
       [1, 0, 2]])

In [37]:
inv_b = np.linalg.inv(b)

In [38]:
b @ inv_b

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.66533454e-16, 1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 0.00000000e+00, 1.00000000e+00]])

In [39]:
# Error karena bukan matrix persegi
np.linalg.inv(n)

LinAlgError: Last 2 dimensions of the array must be square

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

Determinan

In [43]:
x = np.array([[1,2],
            [0,2]])

x

array([[1, 2],
       [0, 2]])

In [44]:
np.linalg.det(x)

2.0

In [45]:
np.linalg.inv(x)

array([[ 1. , -1. ],
       [ 0. ,  0.5]])

In [47]:
y = np.array([[1,2],
               [2,4]])

y

array([[1, 2],
       [2, 4]])

In [48]:
np.linalg.det(y)

0.0

In [49]:
np.linalg.det(a)

-9.51619735392994e-16

In [ ]:
j = np.([[1,3,4],
        [2,6,3]])

k = np.array